[package]
name = "fwlib"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
flatbuffers = "25.2.10"
hdf5 = { package = "hdf5-metno", version = "0.10.1" }
ndarray = { version = "0.16.1" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
